### ISSUE TITLE
fgallery fails on black an white images

### ISSUE THREAD

**Issue by reald** [wavexx/fgallery#51]
Building gallery fails if there is a black an white images (created with rawtherapee):

```
$>fgallery --max-full 2048x1024 -d test testabg
reading completed                 
[tificc fatal error]: Input profile is not operating in proper color space
error: command "tificc -t0 testabg/files/D30_0442_jrt_sw_b.jpg.tmp testabg/files/D30_0442_jrt_sw_b.jpg.tmp.tmp" failed
```

Concerned image:

```
$>exiftool D30_0442_jrt_sw_b.jpg 
ExifTool Version Number         : 10.10
File Name                       : D30_0442_jrt_sw_b.jpg
Directory                       : .
File Size                       : 680 kB
File Modification Date/Time     : 2016:06:30 17:49:10+02:00
File Access Date/Time           : 2016:06:30 17:49:22+02:00
File Inode Change Date/Time     : 2016:06:30 17:49:10+02:00
File Permissions                : rw-rw-r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : inches
X Resolution                    : 300
Y Resolution                    : 300
Profile CMM Type                : lcms
Profile Version                 : 2.3.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2012:01:15 17:28:16
Profile File Signature          : acsp
Primary Platform                : Microsoft Corporation
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             : LCMS
Device Model                    : 
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : lcms
Profile ID                      : 0
Device Mfg Desc                 : Rawtherapee
Profile Description             : RT_sRGB gamma sRGB(IEC61966 equivalent)
Device Model Desc               : RTsRGB
Media White Point               : 0.95016 1 1.08842
Red Matrix Column               : 0.43585 0.22238 0.01392
Blue Matrix Column              : 0.14302 0.06059 0.71385
Green Matrix Column             : 0.38533 0.71704 0.09712
Red Tone Reproduction Curve     : (Binary data 8204 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 8204 bytes, use -b option to extract)
Blue Tone Reproduction Curve    : (Binary data 8204 bytes, use -b option to extract)
Chromaticity Channels           : 3
Chromaticity Colorant           : Unknown (0)
Chromaticity Channel 1          : 0.64 0.33
Chromaticity Channel 2          : 0.3 0.60001
Chromaticity Channel 3          : 0.14999 0.06
Profile Copyright               : No copyright Rawtherapee -IEC61966 equivalent
Media Black Point               : 0 0 0
Image Width                     : 1040
Image Height                    : 1840
Encoding Process                : Progressive DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
Image Size                      : 1040x1840
Megapixels                      : 1.9
```

tificc is version 6.2 from Package: liblcms2-utils Version: 2.6-3ubuntu2 in Ubuntu 16.04LTS.

**Comment by wavexx** [comment]
A crop of the sample image for testing would be nice.

Also, could you describe which steps did you do in rawtherapee to process/save the image?

**Comment by reald** [comment]
Sample: http://tildepipe.de/public/broken.jpg

Conversion: Open .JPG (not raw) from camera, do some curve processing, Color -> Grayscale -> Channel mixer -> change Gamma -> add to queue -> start waiting queue.

Package: rawtherapee
Version: 4.2-4

**Comment by wavexx** [comment]
This should be fixed now. Can you check?

**Comment by reald** [comment]
Does not work. Version 1.8.2 still fails. Recent github repository segfaults.

**Comment by reald** [comment]
Stepped back, segfault was introduced with c8c74faf2cc72623d3b96af891dee896c85bbea8.

**Comment by wavexx** [comment]
On Tue, Oct 25 2016, reald <notifications@github.com> wrote:
> Does not work. Version 1.8.2 still fails. Recent github repository segfaults.

Can you run perl --version?

**Comment by wavexx** [comment]
On Tue, Oct 25 2016, reald <notifications@github.com> wrote:
> Stepped back, segfault was introduced with c8c74fa.

I assumed that much, but the change is technically correct. I suspect a
specific perl issue, and/or some ABI issue.

Which distro/perl are you using?

**Comment by reald** [comment]
Ubuntu 16.04.1 LTS
Perl v5.22.1

**Comment by reald** [comment]
use open ':locale'; 
seems to be the problem

**Comment by wavexx** [comment]
On Tue, Oct 25 2016, reald <notifications@github.com> wrote:
> use open ':locale';
> seems to be the problem

Looks like the :encoding layer on STDOUT is broken with ithreads at
least before perl 2.24 (I was able to reproduce it on 2.22).

Sigh...

**Comment by wavexx** [comment]
Hopefully worked-around. Could you try again?

**Comment by wavexx** [comment]
Optimistically closing this (confirmed as fixed in #59).
